### ISSUE TITLE
Ruby on Rails Group Project - Kanban Board

### ISSUE THREAD

**Issue by NitBravoA92** [NitBravoA92/recipe-app#17]
# ⭐Kanban Board - Request a Review 👨‍💻

## Project details 📃

- Link the Kanban Board: https://github.com/NitBravoA92/recipe-app/projects/1
- Number of group members: **Two (2) members**:  @NitBravoA92 and @Luffytaro22 
- @NitBravoA92: Team Member 1
- @Luffytaro22: Team Member 2

# To the Reviewer

💝 We really thank 🙇‍♂️ you, dear reviewer 👨‍🎨 for dedicating your precious 🥇 time ⌚ to check this Kanban board 🧾 .

We kindly ask 🙏 dear reviewer 🤵 that if there is any kind of issue 🦯 in this Kanban board, please do list 📃 them in a descriptive 💡 manner and give your best suggestions 🎁 if needed.

If you think some issues are essential to be changed ♻️ please kindly contact 📞 us through Zoom or Slack, We are available on Microverse UTC-6 time zone.

**Comment by danmainah** [comment]
Hi @Luffytaro22 and @NitBravoA92 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️ Added correct info and link on the issue link.
✔️ Created tasks on the Kanban board based on the [project requirements](https://github.com/microverseinc/curriculum-rails/blob/main/recipe-app/buisness_requirements.md).

# Required Changes ♻️

- [ ] @Team Great work adding the public recipe task, however, you forgot to indicate in the description that it should have a link that leads to recipe details, as it's in the project requirement,
     #### Your Task
    ![image](https://github.com/NitBravoA92/recipe-app/assets/61408860/e91ccca3-7baf-4204-b4fa-bba2844d88d8) 

     #### Project requirement
    ![image](https://github.com/NitBravoA92/recipe-app/assets/61408860/752d03b1-7da2-4c29-80ba-921227c5a595)

- [ ] @Team you forgot to add a task to ensure `there are no N+1 queries happening`.
![image](https://github.com/NitBravoA92/recipe-app/assets/61408860/36a88577-d80c-499a-91dd-a1aa022262fa)


_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by NitBravoA92** [comment]
@danmainah Thank you for your suggestions. The changes have been applied.

**Comment by tresorsawasawa** [comment]
# STATUS: APPROVE :heavy_check_mark: :heavy_check_mark:  :champagne: 

Hi @Luffytaro22 and @NitBravoA92 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 :clap: :clap: :100: 

![nodding-yes](https://camo.githubusercontent.com/aced9b1ffa1374fee6c3bcb9689701088f26a09dc5e75eaa59a01fd38ccc26f2/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f766d74786e78766556556f64472f67697068792e676966)

## To highlight :champagne: 
- All requirements are present in your Kanban board :heavy_check_mark: 

## Optional suggestions
_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
